### ISSUE TITLE
Route word mapping include space 

### ISSUE THREAD

**Issue by VimalKumarS** [Graidenix/vanilla-router#10]
hi,

this is very helpful project, to start with any plain javascript project.

trying to set up route as eg:   /app/{{pagename}}/create  (having space in route param)
trying to map the route to /app/admin page/create.  its not mapping pagename with "admin page". its going to 404 page not found route.

Any pointers?

thanks
Vimal

**Comment by Graidenix** [comment]
Hi Vimal,
You can use regex for special rules. 
`router.add(/^hello\/(\w+)/i, function(name){ });`
The default parameters don't include the space, because it is bad practice to use whitespace in URL.

Best regards,
Grigore

PS. Let me know if this is solution worked for you and I can close the ticket.

**Comment by VimalKumarS** [comment]
That works thanks, i dint know regular expression work in library, now i can reduce route mapping 

thanks
